### ISSUE TITLE
Initial task list

### ISSUE THREAD

**Issue by SNMS95** [deepmodeling/jax-fem#1]
- [x] General cleanup + Flake8 file -> Surya
- [x] Enable `pip install` in editable mode [Setup] -> Surya
- [x] Environment file -> Surya
- [x] All tests in one location -> Surya
- [ ] Baseline performance - Memory, Speed & accuracy - benchmark -> Igor
- [ ] GH workflow setup -> Igor
